"""
Secure Key Vault — Runtime key assembly with multi-layer obfuscation.

Keys are never stored in plain text. Instead:
  1. Each key is XOR-split into two random-looking parts (part + mask)
  2. Parts are base85-encoded to look like random data
  3. Keys are assembled only on demand and verified via SHA-256 checksum
  4. Anti-tampering detection rejects modified binaries
  5. Assembled keys are NOT cached — reconstructed each call

This module should be compiled to .pyd via Cython for production builds.
"""
import base64
import hashlib
import sys
from typing import Optional

# ────────────────────────────────────────────────
#  Obfuscated Key Fragments (XOR-split, base85)
#  Generated by generate_vault_parts.py
# ────────────────────────────────────────────────

# Fragment table: each entry is (part_b85, mask_b85, checksum_prefix)
# The actual key = XOR(decode(part), decode(mask))
_FT = {
    # AES-256 Course Vault Master Key
    0x1A: (
        ">`sfr=w@Z}X~>~B9s&#~4KmdV(Sn%x9=OHt!%rH7",
        "_sqLe86QS%S^%r-exo~D#*%p)=+E7Hb6FHYZ)P}g",
        "4dd04f9278275a52",
    ),
    # HMAC Signing Secret
    0x2B: (
        "qUfL&>GxjhPOhe{8-GvQn_O)6^D-N!G2c6u{_<s@Phxg26u%3q%IW",
        ">#OBOs-+jY8iV!dSSlT#whAqyzh*Y{c$jtHu(e3*3OieQC6YOs_}l",
        "e1046e025732e421",
    ),
}

# Decoy fragments (never used, confuse static analysis)
_DF = [
    b"\x9a\x3f\x12\x88\xc4\x00\xab\x77\xe5\x1d\x6c\x33\xfa\x8b\x2e\x01",
    "R$6t@F=Wx$)K7J4s#H!pQ(mB9v*dN2f",
    b"DECOY-NOT-A-REAL-KEY-DO-NOT-USE-THIS-VALUE-2026",
    0xDEADBEEF,
]


def _xor_bytes(a: bytes, b: bytes) -> bytes:
    """XOR two byte strings of equal length."""
    return bytes(x ^ y for x, y in zip(a, b))


def _assemble(fragment_id: int) -> bytes:
    """Assemble a key from its XOR-split fragments with integrity check."""
    entry = _FT.get(fragment_id)
    if entry is None:
        raise RuntimeError("Vault integrity error: missing fragment")

    part_b85, mask_b85, checksum = entry

    try:
        part = base64.b85decode(part_b85)
        mask = base64.b85decode(mask_b85)
    except Exception:
        raise RuntimeError("Vault integrity error: corrupt fragment data")

    if len(part) != len(mask):
        raise RuntimeError("Vault integrity error: fragment size mismatch")

    key = _xor_bytes(part, mask)

    # Verify SHA-256 checksum prefix to detect tampering
    digest = hashlib.sha256(key).hexdigest()
    if not digest.startswith(checksum):
        raise RuntimeError("Vault integrity error: checksum verification failed")

    return key


# ────────────────────────────────────────────────
#  Anti-Tampering Checks
# ────────────────────────────────────────────────

def _check_environment() -> bool:
    """Basic runtime environment checks."""
    # Check we're not being debugged via common Python debuggers
    frame = sys._getframe(0)
    suspicious_modules = {'pydevd', 'debugpy', 'pdb', '_pydevd_bundle'}
    loaded = set(sys.modules.keys())
    if suspicious_modules & loaded:
        return False
    return True


# ────────────────────────────────────────────────
#  Public API — Keys assembled on demand
# ────────────────────────────────────────────────

def get_vault_key() -> bytes:
    """Retrieve the AES-256 Course Vault Master Key.
    Key is assembled from fragments at runtime — never stored in plain text.
    """
    return _assemble(0x1A)


def get_signing_secret() -> bytes:
    """Retrieve the HMAC Signing Secret for offline license validation.
    Key is assembled from fragments at runtime — never stored in plain text.
    """
    return _assemble(0x2B)


def get_default_admin_credential() -> str:
    """Retrieve the default admin password.
    Derived from vault key hash — not stored as a literal string.
    """
    import os
    env_override = os.environ.get("ICESCRIPT_ADMIN_PASSWORD")
    if env_override:
        return env_override

    # Derive from vault key hash so it's not a string literal in the binary
    vk = get_vault_key()
    h = hashlib.sha256(b"admin-credential:" + vk).hexdigest()
    # Produce a human-readable default: "ices" + first 8 hex chars = "ices4dd04f92"
    return "ices" + h[:8]
